#server:
#  port: 8080
#  servlet:
#    contextPath: /
#
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/notebook
#    username: root
#    password: 8450
#
#  security:
#    user:
#      name: user
#      password: 8450
